import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const schemaPath = resolve(__dirname, '../prisma/schema.prisma');
const outputPath = resolve(__dirname, '../../docs/PRISMA_DDL_CONTEXT.md');

function extractModelBlocks(schema: string) {
  const modelRegex = /model\s+(\w+)\s*\{([\s\S]*?)\n\}/g;
  const models: Array<{ name: string; fields: string[] }> = [];

  let match = modelRegex.exec(schema);
  while (match) {
    const [, name, body] = match;
    const fields = body
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('//') && !line.startsWith('@@') && !line.includes('@relation'))
      .map((line) => line.replace(/\s+/g, ' '));

    models.push({ name, fields });
    match = modelRegex.exec(schema);
  }

  return models;
}

function main() {
  const schema = readFileSync(schemaPath, 'utf8');
  const models = extractModelBlocks(schema);

  const selected = models.filter((model) =>
    [
      'Order',
      'Partner',
      'Invoice',
      'Payment',
      'InventoryTransaction',
      'Material',
      'JournalEntry',
      'JournalEntryLine',
      'Account',
    ].includes(model.name),
  );

  const content = [
    '# Prisma DDL Context (AI Read-Only)',
    '',
    'Generated by scripts/export-prisma-ddl-context.ts',
    '',
    ...selected.flatMap((model) => [
      `## ${model.name}`,
      '```txt',
      ...model.fields,
      '```',
      '',
    ]),
  ].join('\n');

  writeFileSync(outputPath, content, 'utf8');
  console.log(`Generated: ${outputPath}`);
}

main();
